### ISSUE TITLE
Not able to control the UR10e and can't connect UR10e with PC 

### ISSUE THREAD

**Issue by tt2cloud** [UniversalRobots/Universal_Robots_ROS_Driver#191] opened 2020-06-10 11:28 UTC
# Summary

Hello, brother,I recently encountered a problem.I am trying to connect PC with UR10e. Following the tutorials, I don't able to the UR10e.I downloaded (https://github.com/UniversalRobots/Universal_Robots_ROS_Driver.git src/Universal_Robots_ROS_Driver) and (https://github.com/fmauch/universal_robot.git src/fmauch_universal_robot) two packages, when I was connecting the PC IP
# Versions
 - ROS Driver version:ubuntu16.04+kinetic
Affected Robot Software Version(s): 5.6.0
Affected Robot Hardware Version(s): UR10e
URCaps Software version(s):external control 1.0.1
robot_ip:=192.18.1.60   PC_ip:=192.168.1.61  
the External_ip:=192.168.1.61 port=50002 

### termial1:roslaunch ur_robot_driver ur10e_bringup.launch robot_ip:=192.168.1.60

auto-starting new master

process[master]: started with pid [16046]

ROS_MASTER_URI=http://localhost:11311

setting /run_id to f9f4466a-aaf6-11ea-87df-c8d9d21823f2

process[rosout-1]: started with pid [16063]

started core service [/rosout]

process[robot_state_publisher-2]: started with pid [16080]

process[ur_hardware_interface-3]: started with pid [16081]

process[ros_control_controller_spawner-4]: started with pid [16082]

[ INFO] [1591778833.244461464]: Main thread: SCHED_FIFO OK

[ INFO] [1591778833.244515999]: Main thread priority is 99

process[ros_control_stopped_spawner-5]: started with pid [16097]

[ INFO] [1591778833.254436740]: Initializing dashboard client

[ INFO] [1591778833.259312031]: Connected: Universal Robots Dashboard Server

process[controller_stopper-6]: started with pid [16133]

process[ur_hardware_interface/ur_robot_state_helper-7]: started with pid [16151]

[ INFO] [1591778833.279400014]: Initializing urdriver

[ INFO] [1591778833.279905846]: Checking if calibration data matches connected robot.

[ INFO] [1591778833.280442042]: Producer thread: SCHED_FIFO OK

[ INFO] [1591778833.280469870]: Thread priority is 99

[ INFO] [1591778833.286314783]: Waiting for controller manager service to come up on /controller_manager/switch_controller

[ INFO] [1591778833.287298633]: waitForService: Service [/controller_manager/switch_controller] has not been advertised, waiting...

[ERROR] [1591778833.342191180]: The calibration parameters of the connected robot don't match the ones from the given kinematics config file. Please be aware that this can lead to critical inaccuracies of tcp positions. Use the ur_calibration tool to extract the correct calibration from the robot and pass that into the description. See [TODO Link to documentation] for details.

[INFO] [1591778833.634791]: Controller Spawner: Waiting for service controller_manager/load_controller

[INFO] [1591778833.691968]: Controller Spawner: Waiting for service controller_manager/load_controller

[ INFO] [1591778834.345545407]: Producer thread: SCHED_FIFO OK

[ INFO] [1591778834.345570416]: Thread priority is 99

[ INFO] [1591778834.389224845]: Setting up RTDE communication with frequency 500.000000

[FATAL] [1591778835.405016530]: Variable 'speed_slider_mask' is currently controlled by another RTDE client. The input recipe can't be used as configured

[ERROR] [1591778835.405094844]: Could not correctly initialize robot. Exiting

================================================================================REQUIRED process [ur_hardware_interface-3] has died!

process has died [pid 16081, exit code 1, cmd /home/yun/catkin_ws7/devel/lib/ur_robot_driver/ur_robot_driver_node __name:=ur_hardware_interface __log:=/home/yun/.ros/log/f9f4466a-aaf6-11ea-87df-c8d9d21823f2/ur_hardware_interface-3.log].

log file: /home/yun/.ros/log/f9f4466a-aaf6-11ea-87df-c8d9d21823f2/ur_hardware_interface-3*.log

Initiating shutdown!

================================================================================

[ur_hardware_interface/ur_robot_state_helper-7] killing on exit

[controller_stopper-6] killing on exit

[ros_control_stopped_spawner-5] killing on exit

[ros_control_controller_spawner-4] killing on exit

[ur_hardware_interface-3] killing on exit

[robot_state_publisher-2] killing on exit

[WARN] [1591778835.978961]: Controller Spawner couldn't find the expected controller_manager ROS interface.

[WARN] [1591778835.978991]: Controller Spawner couldn't find the expected controller_manager ROS interface.

[controller_stopper-6] escalating to SIGTERM

[rosout-1] killing on exit

[master] killing on exit

shutting down processing monitor...

... shutting down processing monitor complete

done

### terminal2:roslaunch ur10_e_moveit_config ur10_e_moveit_planning_execution.launch limited:=true

SUMMARY
PARAMETERS

/move_group/allow_trajectory_execution: True
/move_group/capabilities: move_group/MoveGr...
/move_group/controller_list: [{'action_ns': 'f...
/move_group/endeffector/planner_configs: ['SBLkConfigDefau...
/move_group/jiggle_fraction: 0.05
/move_group/manipulator/default_planner_config: RRTConnectkConfig...
/move_group/manipulator/longest_valid_segment_fraction: 0.01
/move_group/manipulator/planner_configs: ['SBLkConfigDefau...
/move_group/max_range: 5.0
/move_group/max_safe_path_cost: 1
/move_group/moveit_controller_manager: moveit_simple_con...
/move_group/moveit_manage_controllers: True
/move_group/octomap_resolution: 0.025
/move_group/planner_configs/BKPIECEkConfigDefault/border_fraction: 0.9
/move_group/planner_configs/BKPIECEkConfigDefault/failed_expansion_score_factor: 0.5
/move_group/planner_configs/BKPIECEkConfigDefault/min_valid_path_fraction: 0.5
/move_group/planner_configs/BKPIECEkConfigDefault/range: 0.0
/move_group/planner_configs/BKPIECEkConfigDefault/type: geometric::BKPIECE
/move_group/planner_configs/ESTkConfigDefault/goal_bias: 0.05
/move_group/planner_configs/ESTkConfigDefault/range: 0.0
/move_group/planner_configs/ESTkConfigDefault/type: geometric::EST
/move_group/planner_configs/KPIECEkConfigDefault/border_fraction: 0.9
/move_group/planner_configs/KPIECEkConfigDefault/failed_expansion_score_factor: 0.5
/move_group/planner_configs/KPIECEkConfigDefault/goal_bias: 0.05
/move_group/planner_configs/KPIECEkConfigDefault/min_valid_path_fraction: 0.5
/move_group/planner_configs/KPIECEkConfigDefault/range: 0.0
/move_group/planner_configs/KPIECEkConfigDefault/type: geometric::KPIECE
/move_group/planner_configs/LBKPIECEkConfigDefault/border_fraction: 0.9
/move_group/planner_configs/LBKPIECEkConfigDefault/min_valid_path_fraction: 0.5
/move_group/planner_configs/LBKPIECEkConfigDefault/range: 0.0
/move_group/planner_configs/LBKPIECEkConfigDefault/type: geometric::LBKPIECE
/move_group/planner_configs/PRMkConfigDefault/max_nearest_neighbors: 10
/move_group/planner_configs/PRMkConfigDefault/type: geometric::PRM
/move_group/planner_configs/PRMstarkConfigDefault/type: geometric::PRMstar
/move_group/planner_configs/RRTConnectkConfigDefault/range: 0.0
/move_group/planner_configs/RRTConnectkConfigDefault/type: geometric::RRTCon...
/move_group/planner_configs/RRTkConfigDefault/goal_bias: 0.05
/move_group/planner_configs/RRTkConfigDefault/range: 0.0
/move_group/planner_configs/RRTkConfigDefault/type: geometric::RRT
/move_group/planner_configs/RRTstarkConfigDefault/delay_collision_checking: 1
/move_group/planner_configs/RRTstarkConfigDefault/goal_bias: 0.05
/move_group/planner_configs/RRTstarkConfigDefault/range: 0.0
/move_group/planner_configs/RRTstarkConfigDefault/type: geometric::RRTstar
/move_group/planner_configs/SBLkConfigDefault/range: 0.0
/move_group/planner_configs/SBLkConfigDefault/type: geometric::SBL
/move_group/planner_configs/TRRTkConfigDefault/frountierNodeRatio: 0.1
/move_group/planner_configs/TRRTkConfigDefault/frountier_threshold: 0.0
/move_group/planner_configs/TRRTkConfigDefault/goal_bias: 0.05
/move_group/planner_configs/TRRTkConfigDefault/init_temperature: 10e-6
/move_group/planner_configs/TRRTkConfigDefault/k_constant: 0.0
/move_group/planner_configs/TRRTkConfigDefault/max_states_failed: 10
/move_group/planner_configs/TRRTkConfigDefault/min_temperature: 10e-10
/move_group/planner_configs/TRRTkConfigDefault/range: 0.0
/move_group/planner_configs/TRRTkConfigDefault/temp_change_factor: 2.0
/move_group/planner_configs/TRRTkConfigDefault/type: geometric::TRRT
/move_group/planning_plugin: ompl_interface/OM...
/move_group/planning_scene_monitor/publish_geometry_updates: True
/move_group/planning_scene_monitor/publish_planning_scene: True
/move_group/planning_scene_monitor/publish_state_updates: True
/move_group/planning_scene_monitor/publish_transforms_updates: True
/move_group/request_adapters: default_planner_r...
/move_group/start_state_max_bounds_error: 0.1
/move_group/trajectory_execution/allowed_execution_duration_scaling: 1.2
/move_group/trajectory_execution/allowed_goal_duration_margin: 0.5
/move_group/trajectory_execution/execution_duration_monitoring: False
/move_group/use_controller_manager: False
/robot_description_kinematics/manipulator/kinematics_solver: kdl_kinematics_pl...
/robot_description_kinematics/manipulator/kinematics_solver_attempts: 3
/robot_description_kinematics/manipulator/kinematics_solver_search_resolution: 0.005
/robot_description_kinematics/manipulator/kinematics_solver_timeout: 0.005
/robot_description_planning/joint_limits/elbow_joint/has_acceleration_limits: True
/robot_description_planning/joint_limits/elbow_joint/has_velocity_limits: True
/robot_description_planning/joint_limits/elbow_joint/max_acceleration: 3.14
/robot_description_planning/joint_limits/elbow_joint/max_velocity: 3.14
/robot_description_planning/joint_limits/shoulder_lift_joint/has_acceleration_limits: True
/robot_description_planning/joint_limits/shoulder_lift_joint/has_velocity_limits: True
/robot_description_planning/joint_limits/shoulder_lift_joint/max_acceleration: 3.14
/robot_description_planning/joint_limits/shoulder_lift_joint/max_velocity: 3.14
/robot_description_planning/joint_limits/shoulder_pan_joint/has_acceleration_limits: True
/robot_description_planning/joint_limits/shoulder_pan_joint/has_velocity_limits: True
/robot_description_planning/joint_limits/shoulder_pan_joint/max_acceleration: 3.14
/robot_description_planning/joint_limits/shoulder_pan_joint/max_velocity: 3.14
/robot_description_planning/joint_limits/wrist_1_joint/has_acceleration_limits: True
/robot_description_planning/joint_limits/wrist_1_joint/has_velocity_limits: True
/robot_description_planning/joint_limits/wrist_1_joint/max_acceleration: 3.14
/robot_description_planning/joint_limits/wrist_1_joint/max_velocity: 6.28
/robot_description_planning/joint_limits/wrist_2_joint/has_acceleration_limits: True
/robot_description_planning/joint_limits/wrist_2_joint/has_velocity_limits: True
/robot_description_planning/joint_limits/wrist_2_joint/max_acceleration: 3.14
/robot_description_planning/joint_limits/wrist_2_joint/max_velocity: 6.28
/robot_description_planning/joint_limits/wrist_3_joint/has_acceleration_limits: True
/robot_description_planning/joint_limits/wrist_3_joint/has_velocity_limits: True
/robot_description_planning/joint_limits/wrist_3_joint/max_acceleration: 3.14
/robot_description_planning/joint_limits/wrist_3_joint/max_velocity: 6.28
/robot_description_semantic: <?xml version="1....
/rosdistro: kinetic
/rosversion: 1.12.14
NODES
/
move_group (moveit_ros_move_group/move_group)

ROS_MASTER_URI=http://localhost:11311

run_id on parameter server does not match declared run_id: f9f4466a-aaf6-11ea-87df-c8d9d21823f2 vs fa6e0978-aaf6-11ea-87df-c8d9d21823f2
The traceback for the exception was written to the log file
### termial3:roslaunch ur10_e_moveit_config moveit_rviz.launch
SUMMARY
PARAMETERS

/rosdistro: kinetic
/rosversion: 1.12.14
/rviz_yun_HP_EliteDesk_800_G4_TWR_16141_4429582541512616018/manipulator/kinematics_solver: kdl_kinematics_pl...
/rviz_yun_HP_EliteDesk_800_G4_TWR_16141_4429582541512616018/manipulator/kinematics_solver_attempts: 3
/rviz_yun_HP_EliteDesk_800_G4_TWR_16141_4429582541512616018/manipulator/kinematics_solver_search_resolution: 0.005
/rviz_yun_HP_EliteDesk_800_G4_TWR_16141_4429582541512616018/manipulator/kinematics_solver_timeout: 0.005
NODES
/
rviz_yun_HP_EliteDesk_800_G4_TWR_16141_4429582541512616018 (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

process[rviz_yun_HP_EliteDesk_800_G4_TWR_16141_4429582541512616018-1]: started with pid [16294]
[ INFO] [1591778834.186943878]: rviz version 1.12.17
[ INFO] [1591778834.187022497]: compiled against Qt version 5.5.1
[ INFO] [1591778834.187047235]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1591778834.483021439]: Stereo is NOT SUPPORTED
[ INFO] [1591778834.483084141]: OpenGl version: 3 (GLSL 1.3).
[ERROR] [1591778835.330058916]: Robot semantic description not found. Did you forget to define or remap '/robot_description_semantic'?
[ INFO] [1591778835.330242282]: Loading robot model 'ur10e'...
[ INFO] [1591778835.330292133]: No root/virtual joint specified in SRDF. Assuming fixed joint

**The TP show don't connect to the remote PC establish.
Could you help me ,this question has really been bothering me, thanks advance!@fmauch@gavanderhoorn@Csp0920**

**Comment by fmauch** [comment] 2020-06-11 18:55
The error message you encounter says that there is another RTDE client controlling the speed slider.

Can you confirm that there is no other URcap installed on the robot and there is no other clie nt connected over RTDE?

**Comment by gavanderhoorn** [comment] 2020-06-11 18:58
Could this be EtherNet/IP again perhaps? Or Profinet?

**Comment by fmauch** [comment] 2020-06-12 05:30
> Could this be EtherNet/IP again perhaps? Or Profinet?

I would not rule out that possibility. @tt2cloud Is any fieldbus enabled (Installation -> Fieldbus)?

**Comment by pradeepr-roboticist** [comment] 2020-06-13 20:17
> The error message you encounter says that there is another RTDE client controlling the speed slider.
> 
> Can you confirm that there is no other URcap installed on the robot and there is no other clie nt connected over RTDE?

I am having the same issue. I got the same error message regarding the RTDE and 'speed_slider_mask'. I do not have any other program running that uses RTDE.
I traced it down to the "rtde_input_receipe.txt". Just for debugging, I removed all of the text in receipe.txt; still did not workout. But, I guess I hit a roadblock at that point.

I desperately need this driver to work. I am not allowed to use the older "ur_modern_driver" due to certain restrictions at my workplace and the fact that it does not support speed commands. And, I even resorted to talking directly via the RTDE client API but found no luck in making it work. Any suggestions would be welcome.

If it helps, here are some settings I have:
Hardware: UR5 CB3
Polyscope version: 3.7
OS: Ubuntu 18.04
ROS: Melodic

EtherNet/IP is enabled
PROFINET: Disabled
MODBUS: Disabled

Robot IP: 192.168.1.3
Desktop IP: 192.168.1.2

I do not appear to have the "Fieldbus" option.

Here are the error messages I received when I tried ur5_bringup.launch :
============================================================
[ INFO] [1592078115.878362080]: Initializing urdriver
[ INFO] [1592078115.878673261]: Checking if calibration data matches connected robot.
[ WARN] [1592078115.878962471]: No realtime capabilities found. Consider using a realtime system for better performance
[ INFO] [1592078115.883056940]: Waiting for controller manager service to come up on /controller_manager/switch_controller
[ INFO] [1592078115.884002996]: waitForService: Service [/controller_manager/switch_controller] has not been advertised, waiting...
[INFO] [1592078116.152466]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1592078116.157702]: Controller Spawner: Waiting for service controller_manager/load_controller
[ INFO] [1592078116.205561079]: Calibration checked successfully.
[ WARN] [1592078116.907728617]: No realtime capabilities found. Consider using a realtime system for better performance
[ INFO] [1592078117.003019754]: Negotiated RTDE protocol version to 2.
[ INFO] [1592078117.003538817]: Setting up RTDE communication with frequency 125.000000
[FATAL] [1592078118.005495009]: Variable 'speed_slider_mask' is currently controlled by another RTDE client. The input recipe can't be used as configured
[ERROR] [1592078118.005662044]: Could not correctly initialize robot. Exiting
================================================================================REQUIRED process [ur_hardware_interface-3] has died!
process has died [pid 8366, exit code 1, cmd /home/pradeepr/Desktop/test_ws/devel/lib/ur_robot_driver/ur_robot_driver_node __name:=ur_hardware_interface __log:=/home/pradeepr/.ros/log/cc69506c-adaf-11ea-a7d7-1866da1cb998/ur_hardware_interface-3.log].
log file: /home/pradeepr/.ros/log/cc69506c-adaf-11ea-a7d7-1866da1cb998/ur_hardware_interface-3*.log
Initiating shutdown!
================================================================================
[ur_hardware_interface/ur_robot_state_helper-7] killing on exit
[controller_stopper-6] killing on exit
[ros_control_stopped_spawner-5] killing on exit
[ros_control_controller_spawner-4] killing on exit
[ur_hardware_interface-3] killing on exit
[robot_state_publisher-2] killing on exit
[WARN] [1592078118.361305]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[WARN] [1592078118.877379]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[controller_stopper-6] escalating to SIGTERM
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
=========================================================================


Thanks for your help.

**Comment by fmauch** [comment] 2020-06-14 19:26
> EtherNet/IP is enabled
PROFINET: Disabled
MODBUS: Disabled

>...

>I do not appear to have the "Fieldbus" option.

@pradeepr-roboticist  You seem to indeed have a Fieldbus enabled, namely EtherNet/IP. On a CB3 polyscope the fieldbusses are not under a separate subentry, but are listed inside the Installation menu. Also see the according [troubleshooting entry](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver#when-starting-the-program-on-the-tp-i-get-a-c207a0-error).

Could you try to disable the EtherNet/IP fieldbus and then try again, please?

**Comment by tt2cloud** [comment] 2020-06-15 00:55
> The error message you encounter says that there is another RTDE client controlling the speed slider.
> 
> Can you confirm that there is no other URcap installed on the robot and there is no other clie nt connected over RTDE?

Year that's right .
Now I can successfully connect my pc with ur10e.Thanks for your help

**Comment by tt2cloud** [comment] 2020-06-15 00:57
> > EtherNet/IP is enabled
> > PROFINET: Disabled
> > MODBUS: Disabled
> 
> > ...
> 
> > I do not appear to have the "Fieldbus" option.
> 
> @pradeepr-roboticist You seem to indeed have a Fieldbus enabled, namely EtherNet/IP. On a CB3 polyscope the fieldbusses are not under a separate subentry, but are listed inside the Installation menu. Also see the according [troubleshooting entry](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver#when-starting-the-program-on-the-tp-i-get-a-c207a0-error).
> 
> Could you try to disable the EtherNet/IP fieldbus and then try again, please?

Thanks you help, I can successfully connect my pc with ur10e

**Comment by pradeepr-roboticist** [comment] 2020-06-15 02:28
> > EtherNet/IP is enabled
> > PROFINET: Disabled
> > MODBUS: Disabled
> 
> > ...
> 
> > I do not appear to have the "Fieldbus" option.
> 
> @pradeepr-roboticist You seem to indeed have a Fieldbus enabled, namely EtherNet/IP. On a CB3 polyscope the fieldbusses are not under a separate subentry, but are listed inside the Installation menu. Also see the according [troubleshooting entry](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver#when-starting-the-program-on-the-tp-i-get-a-c207a0-error).
> 
> Could you try to disable the EtherNet/IP fieldbus and then try again, please?

Wow! Thank you so much for your time! I am now able to connect.

**Comment by gavanderhoorn** [comment] 2020-06-15 07:29
@fmauch: would we already have an idea what causes the fieldbus setup / daemon to interfere here?

**Comment by fmauch** [comment] 2020-06-15 07:39
I wanted to investigate this today.

**Comment by tt2cloud** [comment] 2020-06-15 12:13
> > Could this be EtherNet/IP again perhaps? Or Profinet?
> 
> I would not rule out that possibility. @tt2cloud Is any fieldbus enabled (Installation -> Fieldbus)?

This problem has been sloved,thank you !
But,, I met another difficulty.Could you help me [(https://github.com/ros-controls/ros_control/issues/465)]

**Comment by fmauch** [comment] 2020-06-15 12:35
I confirm that as soon as EtherNet/IP is enabled, all RTDE inputs (at least the ones used by the recipe) are marked `IN_USE`

```
[ INFO] [1592224509.216983662]: speed_slider_mask confirmed as datatype: IN_USE
[ INFO] [1592224509.217059164]: speed_slider_fraction confirmed as datatype: IN_USE
[ INFO] [1592224509.217087356]: standard_digital_output_mask confirmed as datatype: IN_USE
[ INFO] [1592224509.217110027]: standard_digital_output confirmed as datatype: IN_USE
[ INFO] [1592224509.217139018]: configurable_digital_output_mask confirmed as datatype: IN_USE
[ INFO] [1592224509.217160624]: configurable_digital_output confirmed as datatype: IN_USE
[ INFO] [1592224509.217180648]: tool_digital_output_mask confirmed as datatype: IN_USE
[ INFO] [1592224509.217211312]: tool_digital_output confirmed as datatype: IN_USE
[ INFO] [1592224509.217232307]: standard_analog_output_mask confirmed as datatype: IN_USE
[ INFO] [1592224509.217260886]: standard_analog_output_type confirmed as datatype: IN_USE
[ INFO] [1592224509.217281989]: standard_analog_output_0 confirmed as datatype: IN_USE
[ INFO] [1592224509.217307054]: standard_analog_output_1 confirmed as datatype: IN_USE
```

**Comment by gavanderhoorn** [comment] 2020-06-15 13:00
Hm, weird.

Is this expected behaviour/documented?

**Comment by fmauch** [comment] 2020-06-15 13:47
I've searched around but couldn't find anything in the documentation. I'll come back to this when I know more.

**Comment by tt2cloud** [comment] 2020-06-17 01:06
> > Could this be EtherNet/IP again perhaps? Or Profinet?
> 
> I would not rule out that possibility. @tt2cloud Is any fieldbus enabled (Installation -> Fieldbus)?

Brother,could you help me solve the problems, I have no idea.
When I can moved the model under the rviz, but the real Hardware can't move
(https://github.com/ros-controls/ros_control/issues/465)   
Thanks in advance!

**Comment by fmauch** [comment] 2020-06-18 13:29
Closing, as one part is duplicate of #195 and second part is handled in #200

**Closed by fmauch** 2020-06-18 13:29 UTC
