### ISSUE TITLE
UR5e + 2F_85 Robotiq Gripper control from ROS pc

### ISSUE THREAD

**Issue by rrapi** [UniversalRobots/Universal_Robots_ROS_Driver#518] opened 2022-04-07 18:24 UTC
# Summary

Hi everyone!!

I am a master science student working on my thesis and in our lab we have a UR5e and Robotiq 2F_85 Gripper attached directly to the robot control box.

I set all the things and the configuration (I followed the readme tutorial of this repository) seems to work for the robot that I can control and send commands to it from my ROS Pc, even from RViz. But not the same for the Gripper. I tried with tool_communication of ur_robot_driver and even with the robotiq_2f_gripper_control_driver but still does not work and cannot control the gripper.

For this problem I have some questions that would help me a lot to solve it:

1. Is it possible to control the gripper directly attached to robot control box? 
2. If yes, could you please explain me how to do that work properly?
3. Or connecting the gripper directly to the USB of the ROS pc is the only way?

# Versions
 - ROS Driver version: Melodic
 - Affected Robot Software Version(s): 5.11
 - Affected Robot Hardware Version(s): UR5e
 - Robot Serial Number:
 - UR+ product(s) installed:
 - URCaps Software version(s): external control (1.0.5), RS485 (1.0.0)

The ROS pc that I am using is Ubuntu 18.04 with Melodic. 
I hope I have explained the problem as well as possible and that you could help me.

Thank you very much for your time!

Franci

**Comment by fmauch** [comment] 2022-04-08 07:21
Duplicate of #506

You have already posted a question in #506, please do not open duplicated issues.

For the 3rd option, please use the gripper normally as explained in the [tutorial](https://wiki.ros.org/robotiq/Tutorials/Control%20of%20a%202-Finger%20Gripper%20using%20the%20Modbus%20RTU%20protocol%20%28ros%20kinetic%20and%20newer%20releases%29)

**Closed by fmauch** 2022-04-08 07:21 UTC
