### ISSUE TITLE
Could not get fresh data package from robot when PROFINET is enabled

### ISSUE THREAD

**Issue by megantuttle** [UniversalRobots/Universal_Robots_ROS_Driver#56] opened 2019-12-05 20:45 UTC
Upon attempting to set the tool digital output via the `/ur_hardware_interface/set_io` service, the driver throws an error:
``` [ERROR] [1575562385.903592318]: Could not get fresh data package from robot ```
and the output remains the same, although the service call returns `success: True`.

### Versions
 - Affected Robot Software Version(s): 3.11.0.82155
 - Affected Robot Hardware Version(s): UR3 CB-series

### Use Case and Setup
 - ROS Kinetic
 - Ubuntu 16.04.6

### Issue details
Terminal output from driver launch:
```
arw@arw-pc:~$ roslaunch ur_robot_driver ur3_bringup.launch
... logging to /home/arw/.ros/log/04cf3074-177a-11ea-9bba-7085c275eb55/roslaunch-arw-pc-121002.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://arw-pc:36045/

SUMMARY
========

PARAMETERS
 * /controller_stopper/consistent_controllers: ['joint_state_con...
 * /force_torque_sensor_controller/publish_rate: 125
 * /force_torque_sensor_controller/type: force_torque_sens...
 * /hardware_control_loop/loop_hz: 125
 * /hardware_interface/joints: ['shoulder_pan_jo...
 * /joint_state_controller/publish_rate: 125
 * /joint_state_controller/type: joint_state_contr...
 * /pos_traj_controller/action_monitor_rate: 10
 * /pos_traj_controller/constraints/elbow_joint/goal: 0.1
 * /pos_traj_controller/constraints/elbow_joint/trajectory: 0.2
 * /pos_traj_controller/constraints/goal_time: 0.6
 * /pos_traj_controller/constraints/shoulder_lift_joint/goal: 0.1
 * /pos_traj_controller/constraints/shoulder_lift_joint/trajectory: 0.2
 * /pos_traj_controller/constraints/shoulder_pan_joint/goal: 0.1
 * /pos_traj_controller/constraints/shoulder_pan_joint/trajectory: 0.2
 * /pos_traj_controller/constraints/stopped_velocity_tolerance: 0.05
 * /pos_traj_controller/constraints/wrist_1_joint/goal: 0.1
 * /pos_traj_controller/constraints/wrist_1_joint/trajectory: 0.2
 * /pos_traj_controller/constraints/wrist_2_joint/goal: 0.1
 * /pos_traj_controller/constraints/wrist_2_joint/trajectory: 0.2
 * /pos_traj_controller/constraints/wrist_3_joint/goal: 0.1
 * /pos_traj_controller/constraints/wrist_3_joint/trajectory: 0.2
 * /pos_traj_controller/joints: ['shoulder_pan_jo...
 * /pos_traj_controller/state_publish_rate: 125
 * /pos_traj_controller/stop_trajectory_duration: 0.5
 * /pos_traj_controller/type: position_controll...
 * /robot_description: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /scaled_pos_traj_controller/action_monitor_rate: 10
 * /scaled_pos_traj_controller/constraints/elbow_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/elbow_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/constraints/goal_time: 0.6
 * /scaled_pos_traj_controller/constraints/shoulder_lift_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/shoulder_lift_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/constraints/shoulder_pan_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/shoulder_pan_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/constraints/stopped_velocity_tolerance: 0.05
 * /scaled_pos_traj_controller/constraints/wrist_1_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/wrist_1_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/constraints/wrist_2_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/wrist_2_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/constraints/wrist_3_joint/goal: 0.1
 * /scaled_pos_traj_controller/constraints/wrist_3_joint/trajectory: 0.2
 * /scaled_pos_traj_controller/joints: ['shoulder_pan_jo...
 * /scaled_pos_traj_controller/state_publish_rate: 125
 * /scaled_pos_traj_controller/stop_trajectory_duration: 0.5
 * /scaled_pos_traj_controller/type: position_controll...
 * /speed_scaling_state_controller/publish_rate: 125
 * /speed_scaling_state_controller/type: ur_controllers/Sp...
 * /ur_hardware_interface/headless_mode: False
 * /ur_hardware_interface/input_recipe_file: /home/arw/arw_ws/...
 * /ur_hardware_interface/kinematics/forearm/pitch: -0.000287220857793
 * /ur_hardware_interface/kinematics/forearm/roll: 0.00170357346687
 * /ur_hardware_interface/kinematics/forearm/x: -0.244144204868
 * /ur_hardware_interface/kinematics/forearm/y: 0
 * /ur_hardware_interface/kinematics/forearm/yaw: 3.4308906525e-05
 * /ur_hardware_interface/kinematics/forearm/z: 0
 * /ur_hardware_interface/kinematics/hash: calib_26724891755...
 * /ur_hardware_interface/kinematics/shoulder/pitch: 0
 * /ur_hardware_interface/kinematics/shoulder/roll: 0
 * /ur_hardware_interface/kinematics/shoulder/x: 0
 * /ur_hardware_interface/kinematics/shoulder/y: 0
 * /ur_hardware_interface/kinematics/shoulder/yaw: -3.5287597596e-05
 * /ur_hardware_interface/kinematics/shoulder/z: 0.151662308025
 * /ur_hardware_interface/kinematics/upper_arm/pitch: 0
 * /ur_hardware_interface/kinematics/upper_arm/roll: 1.57022507232
 * /ur_hardware_interface/kinematics/upper_arm/x: -0.000152885195491
 * /ur_hardware_interface/kinematics/upper_arm/y: 0
 * /ur_hardware_interface/kinematics/upper_arm/yaw: -2.50883048411e-05
 * /ur_hardware_interface/kinematics/upper_arm/z: 0
 * /ur_hardware_interface/kinematics/wrist_1/pitch: 0.00399495497907
 * /ur_hardware_interface/kinematics/wrist_1/roll: 0.000456686827944
 * /ur_hardware_interface/kinematics/wrist_1/x: -0.213136605359
 * /ur_hardware_interface/kinematics/wrist_1/y: -5.16786677365e-05
 * /ur_hardware_interface/kinematics/wrist_1/yaw: -7.1582639858e-06
 * /ur_hardware_interface/kinematics/wrist_1/z: 0.113159962104
 * /ur_hardware_interface/kinematics/wrist_2/pitch: 0
 * /ur_hardware_interface/kinematics/wrist_2/roll: 1.5724288729
 * /ur_hardware_interface/kinematics/wrist_2/x: 0.000163824547616
 * /ur_hardware_interface/kinematics/wrist_2/y: -0.0851991182172
 * /ur_hardware_interface/kinematics/wrist_2/yaw: 9.47060355652e-06
 * /ur_hardware_interface/kinematics/wrist_2/z: -0.000139091612134
 * /ur_hardware_interface/kinematics/wrist_3/pitch: 3.14159265359
 * /ur_hardware_interface/kinematics/wrist_3/roll: 1.56989500609
 * /ur_hardware_interface/kinematics/wrist_3/x: 2.18218802874e-06
 * /ur_hardware_interface/kinematics/wrist_3/y: 0.0821902302805
 * /ur_hardware_interface/kinematics/wrist_3/yaw: -3.14154790558
 * /ur_hardware_interface/kinematics/wrist_3/z: -7.40797765348e-05
 * /ur_hardware_interface/output_recipe_file: /home/arw/arw_ws/...
 * /ur_hardware_interface/robot_ip: 192.168.1.10
 * /ur_hardware_interface/script_file: /home/arw/arw_ws/...
 * /ur_hardware_interface/tf_prefix: 
 * /ur_hardware_interface/tool_baud_rate: 115200
 * /ur_hardware_interface/tool_parity: 0
 * /ur_hardware_interface/tool_rx_idle_chars: 1.5
 * /ur_hardware_interface/tool_stop_bits: 1
 * /ur_hardware_interface/tool_tx_idle_chars: 3.5
 * /ur_hardware_interface/tool_voltage: 0
 * /ur_hardware_interface/use_tool_communication: False

NODES
  /
    controller_stopper (controller_stopper/node)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    ros_control_controller_spawner (controller_manager/spawner)
    ros_control_stopped_spawner (controller_manager/spawner)
    ur_hardware_interface (ur_robot_driver/ur_robot_driver_node)
  /ur_hardware_interface/
    ur_robot_state_helper (ur_robot_driver/robot_state_helper)

auto-starting new master
process[master]: started with pid [121016]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 04cf3074-177a-11ea-9bba-7085c275eb55
process[rosout-1]: started with pid [121029]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [121046]
process[ur_hardware_interface-3]: started with pid [121047]
process[ros_control_controller_spawner-4]: started with pid [121048]
process[ros_control_stopped_spawner-5]: started with pid [121061]
process[controller_stopper-6]: started with pid [121073]
process[ur_hardware_interface/ur_robot_state_helper-7]: started with pid [121077]
[ INFO] [1575562343.876588465]: Waiting for controller manager service to come up on /controller_manager/switch_controller
[ INFO] [1575562343.877356445]: waitForService: Service [/controller_manager/switch_controller] has not been advertised, waiting...
[INFO] [1575562344.333276]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1575562344.334390]: Controller Spawner: Waiting for service controller_manager/load_controller
[ INFO] [1575562344.772292211]: Main thread: SCHED_FIFO OK
[ INFO] [1575562344.772428114]: Main thread priority is 99
[ INFO] [1575562344.782756884]: Initializing dashboard client
[ INFO] [1575562344.784673134]: Connected: Universal Robots Dashboard Server

[ INFO] [1575562344.812152327]: Initializing urdriver
[ INFO] [1575562344.812490540]: Checking if calibration data matches connected robot.
[ INFO] [1575562344.813330719]: Producer thread: SCHED_FIFO OK
[ INFO] [1575562344.813380228]: Thread priority is 99
[ INFO] [1575562344.930862750]: Calibration checked successfully.
[ INFO] [1575562345.832844849]: Producer thread: SCHED_FIFO OK
[ INFO] [1575562345.832879762]: Thread priority is 99
[ INFO] [1575562346.352666664]: Setting up RTDE communication with frequency 125.000000
[ INFO] [1575562347.396904901]: Producer thread: SCHED_FIFO OK
[ INFO] [1575562347.396941506]: Thread priority is 99
[ INFO] [1575562347.397008105]: Loaded ur_robot_driver hardware_interface
[ INFO] [1575562347.464295751]: waitForService: Service [/controller_manager/switch_controller] is now available.
[ INFO] [1575562347.464340681]: Service available.
[ INFO] [1575562347.464367349]: Waiting for controller list service to come up on /controller_manager/list_controllers
[ INFO] [1575562347.465924928]: Service available.
[ INFO] [1575562347.639440003]: Robot's safety mode is now NORMAL
[ INFO] [1575562347.639986418]: Robot mode is now RUNNING
[INFO] [1575562347.670039]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1575562347.672224]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1575562347.673714]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1575562347.674900]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1575562347.676547]: Loading controller: joint_state_controller
[INFO] [1575562347.677481]: Loading controller: pos_traj_controller
[INFO] [1575562347.693851]: Loading controller: scaled_pos_traj_controller
[INFO] [1575562347.805735]: Controller Spawner: Loaded controllers: pos_traj_controller
[INFO] [1575562348.021409]: Loading controller: speed_scaling_state_controller
[INFO] [1575562348.029785]: Loading controller: force_torque_sensor_controller
[INFO] [1575562348.045608]: Controller Spawner: Loaded controllers: joint_state_controller, scaled_pos_traj_controller, speed_scaling_state_controller, force_torque_sensor_controller
[INFO] [1575562348.053596]: Started controllers: joint_state_controller, scaled_pos_traj_controller, speed_scaling_state_controller, force_torque_sensor_controller
[ERROR] [1575562362.355470964]: Could not get fresh data package from robot
```
Terminal output from service call:
```
arw@arw-pc:~$ rosservice call /ur_hardware_interface/set_io "fun: 1
pin: 16
state: true" 
success: True
```
I also tried pin 17 with the same result.
The driver appears to be getting data from the robot because IO states are being published on the `/ur_hardware_interface/io_states` topic.

**Comment by megantuttle** [comment] 2019-12-05 21:00
I resolved this issue. I have Profinet enabled on the robot.  Evidently you cannot control the tool digital outputs via the RTDE interface while Profinet is enabled.  I looked in the [UR documentation on the RTDE interface](https://www.universal-robots.com/how-tos-and-faqs/how-to/ur-how-tos/real-time-data-exchange-rtde-guide-22229/) and didn't find anything that suggested the Profinet interface would take priority or prevent certain outputs from being accessed via the RTDE interface.  I posted this issue to the driver just in case someone else runs into the same problem.  Perhaps the phenomenon could be addressed in the driver by giving a more informative error output; or maybe it could be included in the documentation.

**Comment by fmauch** [comment] 2019-12-06 08:12
This is someting not yet known to us and should definitely be tackled.

Unfortunately, I don't have any PROFINET device here. I cannot reproduce this in URSim. Does this only occur with a connected PROFINET device or can I test this on a real system without a PROFINET device attached?

**Comment by gavanderhoorn** [comment] 2019-12-06 10:45
@fmauch: as we also have #28 there may be some unexpected interactions between the driver and other 'users' of RTDE?

**Comment by fmauch** [comment] 2019-12-06 11:00
Well, #28 was about the missing fieldbus connection ended the program. This one here seems to directly interfer with RTDE data transport in some way, so I think, this is something different.

**Comment by gavanderhoorn** [comment] 2019-12-06 11:03
True.

It would perhaps be good to verify that using EtherNet/IP while the driver is active does not cause similar issues though.

**Comment by fmauch** [comment] 2019-12-06 11:06
> True.
> 
> It would perhaps be good to verify that using EtherNet/IP while the driver is active does not cause similar issues though.

Also true.

**Comment by megantuttle** [comment] 2019-12-10 19:25
@fmauch 
> This is someting not yet known to us and should definitely be tackled.
>
> Unfortunately, I don't have any PROFINET device here. I cannot reproduce this in URSim. Does this only occur with a connected PROFINET device or can I test this on a real system without a PROFINET device attached?

I was able to reproduce the issue by deleting the PROFINET device from the project and simply having PROFINET enabled on the robot.

I also just noticed that enabling PROFINET while the driver is connected causes an error message to appear on the TP.
![IMG_20191210_103309](https://user-images.githubusercontent.com/16921298/70557975-ca0a1b80-1b38-11ea-9939-f6bef78d71e7.jpg)
The error message goes away once I shut down the driver. I'm not sure if that's useful information or not.

**Comment by fmauch** [comment] 2019-12-12 08:12
We checked back and there seem to be conflicts on the IO write access here. Unfortunately, I can't provide an ad-hoc solution for this, but we'll keep following this.

**Comment by fmauch** [comment] 2019-12-16 11:50
Unfortunately I am still not able to reproduce this. As I don't have any PROFINET hardware available, I cannot go any further than enabling PROFINET which will only complain about a "IO device module IO not plugged in" and "IO device module Registers not plugged in".

According to the [UR Profinet Guide](https://www.universal-robots.com/how-tos-and-faqs/how-to/ur-how-tos/profinet-guide-20596/) and the [RTDE documentation](https://www.universal-robots.com/how-tos-and-faqs/how-to/ur-how-tos/real-time-data-exchange-rtde-guide-22229/) the only conflicts could be raised by the `<input/output>_<type>_register_x` fields, which we currently do not use inside the driver.

With implementing #24 conflicts should be visible more clearly, we hope to finish a first implementation within this year.

**Comment by fmauch** [comment] 2020-09-25 07:53
Closing this in ~1week if no new information is coming in.

**Closed** 2020-11-06 09:46 UTC
Labels: close if no update

**Comment by abdul-mannan-khan** [comment] 2020-12-08 08:08
I have a another problem. My PROFINET is disabled still I am getting this error. 

Here is what I am doing:
```
$ roslaunch ur_calibration calibration_correction.launch \robot_ip:=192.168.0.100 \target_filename:="$(rospack find ur_calibration)/etc/ex-ur5_calibration.yaml"
$ roslaunch ur_robot_driver ur5_bringup.launch robot_ip:=192.168.0.100 [reverse_port:=REVERSE_PORT] \kinematics_config:=$(rospack find ur_calibration)/etc/ex-ur5_calibration.yaml
```

But after sometime, I get this error "Could not get fresh data package from robot". My PROFINET is disabled. Any suggestion please? Thank you for reading my query and your interest.

**Comment by fmauch** [comment] 2020-12-09 09:32
@abdul-mannan-khan This could be related, but not necessarily is. Please open a new issue instead of restarting a closed issue with maybe a different topic.
